# Paleta principal do projeto TerraJourney

COR_PRIMARIA = '#1D5E4D'
COR_PRIMARIA_ESCURA = '#0F382B'
COR_PRIMARIA_CLARA = '#3B7E67'

COR_SECUNDARIA = '#B98F53'
COR_SECUNDARIA_ESCURA = '#A38146'
COR_SECUNDARIA_CLARA = '#DDB87E'

# Terracota

COR_TERCIARIA = '#A6533C'
COR_TERCIARIA_ESCURA = '#7D3E30'
COR_TERCIARIA_CLARA = '#C8785F'

COR_NEUTRA_CLARA = '#E0D8B8'
COR_FUNDO_CLARO = '#F3F3EC'

COR_FUNDO = '#0E1511'
COR_FUNDO_SECUNDARIO = '#151E19'

COR_CARD = '#18221C'
COR_CARD_HOVER = '#1D2A22'

COR_TEXTO = '#F3F3EC'
COR_TEXTO_SECUNDARIO = '#D0D4CF'
COR_TEXTO_ESCURO = '#0F382B'

COR_BORDA = '#385343'

COR_DESTAQUE = '#B98F53'
COR_ALERTA = '#DDB87E'


PALETA_PLOTLY = [
    COR_PRIMARIA,
    COR_SECUNDARIA,
    COR_TERCIARIA,
    COR_PRIMARIA_CLARA,
    COR_SECUNDARIA_CLARA,
    COR_TERCIARIA_CLARA,
    COR_PRIMARIA_ESCURA,
    COR_SECUNDARIA_ESCURA,
    COR_TERCIARIA_ESCURA,
]


def obter_tema() -> dict[str, str]:
    return {
        'COR_PRIMARIA': COR_PRIMARIA,
        'COR_PRIMARIA_ESCURA': COR_PRIMARIA_ESCURA,
        'COR_PRIMARIA_CLARA': COR_PRIMARIA_CLARA,

        'COR_SECUNDARIA': COR_SECUNDARIA,
        'COR_SECUNDARIA_ESCURA': COR_SECUNDARIA_ESCURA,
        'COR_SECUNDARIA_CLARA': COR_SECUNDARIA_CLARA,

        'COR_TERCIARIA': COR_TERCIARIA,
        'COR_TERCIARIA_ESCURA': COR_TERCIARIA_ESCURA,
        'COR_TERCIARIA_CLARA': COR_TERCIARIA_CLARA,

        'COR_NEUTRA_CLARA': COR_NEUTRA_CLARA,
        'COR_FUNDO_CLARO': COR_FUNDO_CLARO,

        'COR_FUNDO': COR_FUNDO,
        'COR_FUNDO_SECUNDARIO': COR_FUNDO_SECUNDARIO,

        'COR_CARD': COR_CARD,
        'COR_CARD_HOVER': COR_CARD_HOVER,

        'COR_TEXTO': COR_TEXTO,
        'COR_TEXTO_SECUNDARIO': COR_TEXTO_SECUNDARIO,
        'COR_TEXTO_ESCURO': COR_TEXTO_ESCURO,

        'COR_BORDA': COR_BORDA,
        'COR_DESTAQUE': COR_DESTAQUE,
        'COR_ALERTA': COR_ALERTA
    }
'''
# Paleta de cores do projeto
cor_principal_texto = "#0F382B"
cor_barras_principais = "#1D5E4D"
cor_elementos_secundarios = "#3B7E67"
cor_destaque_media = "#B98F53"
cor_alerta_destaque = "#DDB87E"
'''